qmlbook/qmlbook

- ch01/index.rst
- ch02/index.rst
- ch06/index.rst
Refs:
https://github.com/jryannel/qt5-cadaques/issues/213
https://github.com/jryannel/qt5-cadaques/issues/206
https://github.com/jryannel/qt5-cadaques/issues/111
https://github.com/jryannel/qt5-cadaques/issues/115
> Fix Typos - 01

- ch02/index.rst
back-link: ch02/index.html#hello-world
> This code in particular show a rectangle of 300 x 300 pixel geometry
Actual code example is 360 x 360
> ch02: Typo in helloworld width/height

- it/ch01/index.rst
This draft is to test whether links and html generation are working properly
> add it/ch01 first draft

- en/ch02/index.rst
- en/ch15/index.rst
> Fixed grammar ch15

- it/ch01/index.rst
- it/index.rst
Since I am using a computer-aided-translation system to keep the translation project organised (OmegaT: http://www.omegat.org/en/omegat.html), if you find any issues with the rst files please just mention it to me and I'll get it fixed, because the translated rst is an outputfile for me. Thanks!
> improve it/ch01; change book it title

- en/ch02/index.rst
change the name SQLLite to SQLite
> change the name SQLLite to SQLite

- en/ch15/index.rst
> ch15: some fixes

- en/ch04/index.rst
This way ist much easier to 'get' the note!
> Fixes the example of the exported API note.

- _templates/sidebar.html
> Fix a typo (Italien -> Italian)

- en/ch01/index.rst
- en/ch02/index.rst
- en/ch03/index.rst
- en/ch04/index.rst
- en/ch05/index.rst
- en/ch06/index.rst
- en/ch07/index.rst
- en/ch15/index.rst
Hello Juergen and Johan,
Thank you for writing this tutorial.  I had been floundering, trying to get a grasp of QML, when I found your tutorial.  I have a much better understanding after reading chapters 1-4 of your tutorial.
As I went through the first four chapters, I took the liberty of improving the grammar, word choice, spelling, punctuation, and closeness to idiomatic English.  I am not a professional English editor, nor do I have a degree in anything like English, but I am a native speaker.
I haven't changed what you guys were saying, but I believe that others will find the text more readable if you accept this pull request.  I would like to continue editing the next chapters as I proceed through the tutorial, but I want to know if these edits will be merged or thrown away.
Thank …
> Improve grammar, word choice, spelling, and idiomatic English - Chapters 1-7,15

- en/ch14/index.rst
Read chapter 14 and during this fixed some typos and grammar mistakes
> Fixed typos and grammar mistakes

- en/ch16/index.rst
fixes issue #120
> back-link: en/ch16/index.html#understanding-the-qml-run-time
> 
> "The first on sets" => "The first one sets"
> fix typo in chapter 16

- en/ch02/index.rst
remove extra space in example code
> fixed excessive space in c++ example code

- en/ch01/index.rst
Google says 9M file extension 23M file suffix, hence my choice of the latter.
PS I find the white on light blue for Notes to be difficult to read -- too little contrast.
> Various fixes to the English

- en/ch07/index.rst
fixes issue #117:
> back-link: en/ch07/index.html#shadows
> 
> For this you need can specify -> For this you can specify
> Fix typo in chapter 7.3

- CONTRIBUTING.md
- en/ch01/index.rst
Fixed grammar in Chapter 01
Fixed grammar and spelling in contributions read me
> Grammar and spelling fixes

- index.rst
in ePub, contents doesn't be shown by this error
> add slash("/")  at the tail of img tag to fix error in epub

- docs/canvas/canvas.rst
- docs/dynamicqml/dynamicqml.rst
- docs/fluid/fluid.rst
- docs/fluid/src/animation/AnimationExample.qml
- docs/modelview/modelview.rst
- docs/qmlstart/qmlstart.rst
- docs/start/start.rst
Fixed all issues tagged as typos.
> Fixed typos

- docs/multimedia/multimedia.rst
- docs/multimedia/src/progressbar/main.qml
Closes issues #64, #107, and #173.
> Using seek method instead of position property

- docs/networking/networking.rst
Announcement from TQC/Digia: https://blog.qt.io/blog/2016/01/26/notification-for-all-qt-cloud-services-users/
Fixes #122
> Removing section on engin.io, as it has been decomissioned.

- docs/meetqt/meetqt.rst
Language review. Also changing import version in a code snippet to .12 (to reflect LTS version). This allows for the use of TapHandler instead of MouseArea later on.
> Language review: Meet Qt chapter

- docs/qtcpp/qtcpp.rst
> Language review: Qt CPP chapter

- docs/qtcreator/qtcreator.rst
Includes rephrasing where appropriate to make the text more version
agnostic, and updates to procedures where the Creator UI has changed.
> Language review: Qt Creator chapter

- .gitignore
- docs/canvas/canvas.rst
- docs/conf.py
- docs/meetqt/meetqt.rst
- docs/qtcpp/qtcpp.rst
- docs/qtcreator/qtcreator.rst
Various small fixes related to the merge of the language reviews, but also some convenience (i.e. gitignore) and theme for sphinx.
> Various small fixed

- docs/start/start.rst
Includes updating minor version to .12.
> Language review: Start chapter

- docs/ch02-start/start.rst
width is 640 and height is 480, but the text said it is 360x360
> ch02-start: fix HelloWorld.qml explanation

- docs/ch03-qtcreator/qtcreator.rst
> fix grammar error

- docs/ch02-start/start.rst
Fixed typo errors in chapter 02 - Get Started.
> Fixed Issue #267 & #269
